export const PRODUCT_ADD_STARTED = "PRODUCT_ADD_STARTED"
export const PRODUCT_ADD_SUCCESS = "PRODUCT_ADD_SUCCESS"
export const PRODUCT_ADD_FAILURE = "PRODUCT_ADD_FAILURE"

export const PRODUCT_EDIT_STARTED = "PRODUCT_EDIT_STARTED"
export const PRODUCT_EDIT_SUCCESS = "PRODUCT_EDIT_SUCCESS"
export const PRODUCT_EDIT_FAILURE = "PRODUCT_EDIT_FAILURE"

export const PRODUCT_FILTER = "PRODUCT_FILTER"
